### PR TITLE
Update podfile to latest

### PR DESCRIPTION
**Pull request by amccloud**
The version referenced in the previous Podfile has a dereferencing issue.

### CODE REVIEW

**Comment by rasmuslp** [comment]
For this to be useful in a larger context, the updated podspec needs to be pushed to https://github.com/CocoaPods/Specs

Case in point: I installed from cocoapods, and the dereferencing issue has me fooled for an hour, because I thought the version I had installed was the fixed one.

**Comment by aschuch** [comment]
Thanks for the friendly reminder, @rasmuslp. I've submitted a pull request to the official Specs repo.

**Comment by amccloud** [comment]
They won't accept the PR. I've already tried. Something about being
versioned correctly.

**Comment by aschuch** [comment]
My PR just got merged, see https://github.com/CocoaPods/Specs/commit/4b6f8e3f74ead2eee28d84f918889aa0cdc99cd7 for details.

I had to update the Podspec to reference a tag instead of a commit to make it pass validation.

**Comment by rasmuslp** [comment]
Great :)

**Pull request merged**
