### PR TITLE
Feature/popup appearance

### PR DESCRIPTION
**Pull request by copa**
This PR adds the ability to switch the appearance of the Popop between NSPopoverAppearanceMinimal (Default) and NSPopoverAppearanceHUD.
- NSPopoverAppearanceMinimal - NSPopover Default 
  screen shot 2014-09-01 at 11 09 19
- NSPopoverAppearanceHUD
  screen shot 2014-09-01 at 11 09 28

### CODE REVIEW

**Comment by aschuch** [comment]
Thanks for the PR, thats a really good addition.
Can you make `popoverAppearance` a public property rather than using a setter method? That would make a much nicer API...

**Comment by copa** [comment]
OK, cool. Nice that you are interested in that PR. I did the implementation with setPopoverAppearance because AXStatusItemPopup is only a proxy for that NSPopover property. 

Maybe that is another way of implemention for you:
- AXStatusItemPopup.h
  `@property(nonatomic, strong, readonly) NSPopover *popover;`
- AXStatusItemPopup.m
  `@property(nonatomic, strong, readwrite) NSPopover *popover;`

Then the whole popover is customizable from outside.

**Comment by aschuch** [comment]
Yes that would actually be even nicer...

**Comment by copa** [comment]
Anything elso to do?

**Comment by aschuch** [comment]
Thanks 👍

**Pull request merged**
